// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: pastry.proto

package pb

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type Message_Type int32

const (
	Message_MESSAGE        Message_Type = 0
	Message_NODE_JOIN      Message_Type = 1
	Message_NODE_ANNOUNCE  Message_Type = 2
	Message_NODE_EXIT      Message_Type = 3
	Message_HEARTBEAT      Message_Type = 4
	Message_REPAIR_REQUEST Message_Type = 5
	Message_STATE_REQUEST  Message_Type = 6
	Message_STATE_RESPONSE Message_Type = 7
)

var Message_Type_name = map[int32]string{
	0: "MESSAGE",
	1: "NODE_JOIN",
	2: "NODE_ANNOUNCE",
	3: "NODE_EXIT",
	4: "HEARTBEAT",
	5: "REPAIR_REQUEST",
	6: "STATE_REQUEST",
	7: "STATE_RESPONSE",
}

var Message_Type_value = map[string]int32{
	"MESSAGE":        0,
	"NODE_JOIN":      1,
	"NODE_ANNOUNCE":  2,
	"NODE_EXIT":      3,
	"HEARTBEAT":      4,
	"REPAIR_REQUEST": 5,
	"STATE_REQUEST":  6,
	"STATE_RESPONSE": 7,
}

func (x Message_Type) String() string {
	return proto.EnumName(Message_Type_name, int32(x))
}

func (Message_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_85373c68ed8b9855, []int{0, 0}
}

type Message struct {
	Type                 Message_Type `protobuf:"varint,1,opt,name=type,proto3,enum=pb.Message_Type" json:"type,omitempty"`
	Sender               string       `protobuf:"bytes,2,opt,name=sender,proto3" json:"sender,omitempty"`
	Key                  []byte       `protobuf:"bytes,3,opt,name=key,proto3" json:"key,omitempty"`
	Hops                 uint64       `protobuf:"varint,4,opt,name=hops,proto3" json:"hops,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_85373c68ed8b9855, []int{0}
}
func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (m *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(m, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

func (m *Message) GetType() Message_Type {
	if m != nil {
		return m.Type
	}
	return Message_MESSAGE
}

func (m *Message) GetSender() string {
	if m != nil {
		return m.Sender
	}
	return ""
}

func (m *Message) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *Message) GetHops() uint64 {
	if m != nil {
		return m.Hops
	}
	return 0
}

func init() {
	proto.RegisterEnum("pb.Message_Type", Message_Type_name, Message_Type_value)
	proto.RegisterType((*Message)(nil), "pb.Message")
}

func init() { proto.RegisterFile("pastry.proto", fileDescriptor_85373c68ed8b9855) }

var fileDescriptor_85373c68ed8b9855 = []byte{
	// 244 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x3c, 0x90, 0xc1, 0x4a, 0xfb, 0x40,
	0x18, 0xc4, 0xff, 0x9b, 0xec, 0x3f, 0xa1, 0x9f, 0x6d, 0x59, 0xbf, 0x83, 0xe4, 0x18, 0x8a, 0x87,
	0x9c, 0x72, 0xd0, 0x27, 0x58, 0xf5, 0x43, 0x23, 0x74, 0x53, 0x77, 0xb7, 0xe0, 0xad, 0x34, 0xb8,
	0x28, 0x08, 0x66, 0xc9, 0xe6, 0x92, 0x97, 0xf0, 0x91, 0x45, 0x36, 0xd4, 0xde, 0xe6, 0x37, 0x33,
	0xcc, 0x61, 0x60, 0xe9, 0x8f, 0x61, 0x1c, 0xa6, 0xda, 0x0f, 0xfd, 0xd8, 0x63, 0xe2, 0xbb, 0xcd,
	0x0f, 0x83, 0x7c, 0xeb, 0x42, 0x38, 0xbe, 0x3b, 0xbc, 0x06, 0x3e, 0x4e, 0xde, 0x15, 0xac, 0x64,
	0xd5, 0xfa, 0x46, 0xd4, 0xbe, 0xab, 0x4f, 0x51, 0x6d, 0x27, 0xef, 0xf4, 0x9c, 0xe2, 0x15, 0x64,
	0xc1, 0x7d, 0xbd, 0xb9, 0xa1, 0x48, 0x4a, 0x56, 0x2d, 0xf4, 0x89, 0x50, 0x40, 0xfa, 0xe9, 0xa6,
	0x22, 0x2d, 0x59, 0xb5, 0xd4, 0x51, 0x22, 0x02, 0xff, 0xe8, 0x7d, 0x28, 0x78, 0xc9, 0x2a, 0xae,
	0x67, 0xbd, 0xf9, 0x66, 0xc0, 0xe3, 0x18, 0x5e, 0x40, 0xbe, 0x25, 0x63, 0xe4, 0x23, 0x89, 0x7f,
	0xb8, 0x82, 0x85, 0x6a, 0x1f, 0xe8, 0xf0, 0xdc, 0x36, 0x4a, 0x30, 0xbc, 0x84, 0xd5, 0x8c, 0x52,
	0xa9, 0x76, 0xaf, 0xee, 0x49, 0x24, 0xe7, 0x06, 0xbd, 0x36, 0x56, 0xa4, 0x11, 0x9f, 0x48, 0x6a,
	0x7b, 0x47, 0xd2, 0x0a, 0x8e, 0x08, 0x6b, 0x4d, 0x3b, 0xd9, 0xe8, 0x83, 0xa6, 0x97, 0x3d, 0x19,
	0x2b, 0xfe, 0xc7, 0x11, 0x63, 0xa5, 0xa5, 0xb3, 0x95, 0xc5, 0xda, 0x9f, 0x65, 0x76, 0xad, 0x32,
	0x24, 0xf2, 0x2e, 0x9b, 0xbf, 0xb8, 0xfd, 0x0d, 0x00, 0x00, 0xff, 0xff, 0xc6, 0x7d, 0xb8, 0x2f,
	0x1b, 0x01, 0x00, 0x00,
}
